# Build settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME', '/node_modules/']


# Site settings
title: DevFest Vienna
email: team@devfest.at
description: "DevFest Vienna is part of the GDG DevFest event series all around the world"
baseurl: ""
url: "http://www.devfest.at"
permalink: /blog/:title
googleAnalyticsTrackingId: "UA-21611117-6"
googleAnalyticsSiteUrl: "www.devfest.at"

# Location block
eventLocationName: "TU Wien"
eventLocationAddress: "Gußhausstraße 27-29, 1040 Wien"
eventStartTime: "2018-11-24T10:00"
eventStartTimeHumanReadable: "10:00"
eventEndTime: "2018-11-24T19:00"
eventEndTimeHumanReadable: "19:00"
eventPlaceCoordinates: "48.1964423,16.369645"
mapCenterCoordinates: "48.1964423,16.369645"
mapMobileCenterCoordinates: "48.1964423,16.369645"

# Logistics Location Block
logisticsMapCenterCoordinates: "48.1964423,16.369645"
logisticsMapMobileCenterCoordinates: "48.1964423,16.369645"

#Tweets feed
twitterHashTag: "devfest18"
twitterFeed: "/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Subscribe
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"

# Documents
c4pUrl: "https://cfp.gdg-vienna.at/"
c4sponsorsUrl: "/sponsor"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, Vienna"
twitterAccount: "@DevFestVienna"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus-2014.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter-2014.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook-2014.png"

# Header
eventDate: "24 - 25 November 2018"
typeoutTextValues: '"2", "3", "4", "5", "6", "7", "8"'

# About Event Block
eventName: "DevFest Vienna"

# Team Block
aboutUs: "GDG Vienna, JSUG and AndroidHeads Vienna bring to you this amazing conference. Awesome speakers and lots of fun!"

# Speakers List Block
showSessions: true
thumbnailsFolder: /img/speakers/

# Sessions List Block
thumbnailsSessions: /img/sessions/

# Footer
gplusFollowUsUrl: "https://plus.google.com/+DevFestVienna"
twitterFollowUsUrl: "https://twitter.com/DevFestVienna"
fbFollowUsUrl: "https://facebook.com/DevFestVienna"

# Blog
blogCommentsEnabled: false
discusShortName: "devfestvie"
