#! /bin/sh

# 1. Deploy hosting
npx firebase deploy

# 2. Deploy JSON to Firebase database
npx firebase database:set -y /mobile/sessions .tmp/fb-sessions.json
npx firebase database:set -y /mobile/schedule .tmp/fb-schedule.json
npx firebase database:set -y /mobile/speakers .tmp/fb-speakers.json
